// =====================================================
// FULL CEFR B1 GRAMMAR BANK
// High Quality / Single Correct Answer
// CEFR B1 Compatible
// 100 Questions / No topic field
// =====================================================

window.grammar_B1 = [

{q:"If I ___ enough money, I will travel to Canada.",a:"have",options:["have","had","will have","having"]},
{q:"She ___ TV when I called her.",a:"was watching",options:["watched","was watching","has watched","watching"]},
{q:"I ___ in this city since 2020.",a:"have lived",options:["live","lived","have lived","am living"]},
{q:"You ___ wear a seatbelt while driving.",a:"must",options:["must","can","might","used to"]},
{q:"He ___ coffee, but now he drinks tea.",a:"used to drink",options:["used to drink","is used to drinking","drinks","would"]},
{q:"The book ___ by millions of people every year.",a:"is read",options:["reads","is read","was reading","has read"]},
{q:"She asked me where I ___ from.",a:"was",options:["am","was","were","be"]},
{q:"I enjoy ___ music in my free time.",a:"listening to",options:["listen","listening to","to listen","listened"]},
{q:"This is the restaurant ___ we had dinner yesterday.",a:"where",options:["who","which","where","whose"]},
{q:"The weather is ___ today than yesterday.",a:"better",options:["good","better","best","more good"]},

{q:"I ___ my homework before I went out.",a:"had finished",options:["finished","have finished","had finished","was finishing"]},
{q:"At this time tomorrow, I ___ on the beach.",a:"will be lying",options:["lie","will lie","will be lying","am lying"]},
{q:"You look tired. You ___ go to bed earlier.",a:"should",options:["should","mustn't","can't","used to"]},
{q:"I wish I ___ speak Japanese.",a:"could",options:["can","could","will","am"]},
{q:"The movie was ___ than I expected.",a:"more interesting",options:["interesting","more interesting","most interesting","interestinger"]},
{q:"By next year, she ___ at the company for ten years.",a:"will have worked",options:["works","worked","will work","will have worked"]},
{q:"He said that he ___ busy.",a:"was",options:["is","was","were","be"]},
{q:"If I ___ you, I would study harder.",a:"were",options:["am","was","were","be"]},
{q:"She is afraid ___ spiders.",a:"of",options:["at","for","of","with"]},
{q:"We have lived here ___ five years.",a:"for",options:["since","for","from","during"]},

{q:"The cake smells ___.",a:"delicious",options:["delicious","deliciously","more delicious","delight"]},
{q:"Neither Tom nor Jack ___ coming tonight.",a:"is",options:["are","is","be","were"]},
{q:"I couldn't answer because I ___ the question.",a:"hadn't understood",options:["didn't understand","hadn't understood","don't understand","wasn't understanding"]},
{q:"She ___ dinner when the lights went out.",a:"was cooking",options:["cooked","was cooking","has cooked","had cooked"]},
{q:"The letters ___ tomorrow.",a:"will be sent",options:["send","will send","will be sent","are sending"]},
{q:"I prefer ___ at home tonight.",a:"to stay",options:["stay","staying","to stay","stayed"]},
{q:"That's the boy ___ sister is a doctor.",a:"whose",options:["who","whose","which","where"]},
{q:"You ___ smoke here. It's forbidden.",a:"mustn't",options:["mustn't","should","can","could"]},
{q:"If they had studied harder, they ___ the exam.",a:"would have passed",options:["will pass","would pass","would have passed","passed"]},
{q:"He is interested ___ photography.",a:"in",options:["on","at","in","for"]},

{q:"I have ___ finished my project.",a:"already",options:["already","yet","still","since"]},
{q:"We ___ to the new manager yesterday.",a:"spoke",options:["speak","spoken","spoke","have spoken"]},
{q:"This exercise is not ___ as the previous one.",a:"as difficult",options:["difficult","more difficult","as difficult","most difficult"]},
{q:"The meeting was cancelled ___ the bad weather.",a:"because of",options:["because","because of","although","despite"]},
{q:"I ___ tennis since I was a child.",a:"have played",options:["play","played","have played","am playing"]},
{q:"She told me she ___ help later.",a:"would",options:["will","would","can","could"]},
{q:"You had better ___ now.",a:"leave",options:["leave","to leave","leaving","left"]},
{q:"I am looking forward to ___ you.",a:"seeing",options:["see","to see","seeing","seen"]},
{q:"The car ___ yesterday.",a:"was repaired",options:["repaired","was repaired","has repaired","repairs"]},
{q:"He drives ___ than his brother.",a:"more carefully",options:["careful","more carefully","most carefully","carefully"]},

{q:"We stayed inside ___ it was raining.",a:"because",options:["although","because","despite","however"]},
{q:"I don't have ___ money left.",a:"much",options:["many","much","few","a few"]},
{q:"She ___ in London before moving to Paris.",a:"had lived",options:["lived","has lived","had lived","was living"]},
{q:"By the time we arrived, the film ___ .",a:"had started",options:["started","had started","starts","was starting"]},
{q:"The children were tired, ___ they kept playing.",a:"but",options:["because","although","but","so"]},
{q:"I ___ never been to Italy.",a:"have",options:["am","have","had","was"]},
{q:"He asked me if I ___ English.",a:"spoke",options:["speak","spoke","spoken","speaking"]},
{q:"This is ___ best café in town.",a:"the",options:["a","an","the","no article"]},
{q:"They ___ each other for years.",a:"have known",options:["know","knew","have known","are knowing"]},
{q:"If it rains tomorrow, we ___ home.",a:"will stay",options:["stay","stayed","will stay","would stay"]},

{q:"My sister is good ___ math.",a:"at",options:["in","for","at","with"]},
{q:"The homework ___ by the students now.",a:"is being done",options:["does","is done","is being done","was done"]},
{q:"I would rather ___ a taxi.",a:"take",options:["take","to take","taking","took"]},
{q:"The boy ___ won the race is my cousin.",a:"who",options:["who","whose","where","which"]},
{q:"She is ___ than her older sister.",a:"more confident",options:["confident","more confident","most confident","confidenter"]},
{q:"We were late ___ the traffic.",a:"because of",options:["despite","because","because of","although"]},
{q:"He ___ his keys while he was running.",a:"lost",options:["loses","lost","had lost","was losing"]},
{q:"They ___ dinner when we arrived.",a:"were having",options:["had","have","were having","had had"]},
{q:"The package ___ tomorrow morning.",a:"will arrive",options:["arrive","arrived","will arrive","would arrive"]},
{q:"You ___ eat so much sugar.",a:"shouldn't",options:["shouldn't","must","can","might"]},

{q:"I am not used to ___ early.",a:"waking up",options:["wake up","to wake up","waking up","woke up"]},
{q:"He said he ___ the movie before.",a:"had seen",options:["saw","has seen","had seen","was seeing"]},
{q:"There aren't ___ apples left.",a:"many",options:["much","many","little","few"]},
{q:"The museum, ___ was built in 1900, is very famous.",a:"which",options:["who","whose","which","where"]},
{q:"This exercise is ___ easy.",a:"so",options:["so","such","such a","too much"]},
{q:"It's a ___ trip.",a:"two-day",options:["two-days","two day","two-day","two day's"]},
{q:"She apologized ___ being late.",a:"for",options:["for","to","about","with"]},
{q:"While I ___ home, I saw an accident.",a:"was walking",options:["walked","was walking","have walked","had walked"]},
{q:"If I had more free time, I ___ guitar lessons.",a:"would take",options:["take","would take","will take","took"]},
{q:"The room ___ every day.",a:"is cleaned",options:["cleans","is cleaned","cleaned","was cleaning"]},

{q:"He has worked here ___ 2019.",a:"since",options:["for","since","during","while"]},
{q:"She can speak French, ___ she?",a:"can't",options:["can","can't","doesn't","isn't"]},
{q:"The test was ___ difficult that many students failed.",a:"so",options:["such","so","too","very"]},
{q:"I stopped ___ coffee last year.",a:"drinking",options:["drink","to drink","drinking","drank"]},
{q:"This is the man ___ helped me.",a:"who",options:["whose","where","who","which"]},
{q:"We ___ dinner by the time they arrived.",a:"had finished",options:["finished","have finished","had finished","finish"]},
{q:"I think it ___ rain later.",a:"will",options:["will","would","did","does"]},
{q:"The film was ___ boring that we left early.",a:"so",options:["such","so","too","very"]},
{q:"She is married ___ a doctor.",a:"to",options:["with","to","at","for"]},
{q:"Neither answer is correct, ___?",a:"is it",options:["is it","isn't it","are they","aren't they"]},

{q:"I haven't finished my work ___ .",a:"yet",options:["already","just","yet","still"]},
{q:"The report ___ before the meeting started.",a:"had been completed",options:["completed","was completed","had been completed","has completed"]},
{q:"You look tired. You'd better ___ a break.",a:"take",options:["take","to take","taking","took"]},
{q:"The train arrived ___ time.",a:"on",options:["at","in","on","for"]},
{q:"He isn't tall enough ___ basketball professionally.",a:"to play",options:["play","to play","playing","played"]},
{q:"If you heat water to 100°C, it ___ .",a:"boils",options:["boils","will boil","boiled","would boil"]},
{q:"The company ___ a new product next month.",a:"is launching",options:["launch","launched","is launching","would launch"]},
{q:"The teacher made the students ___ the exercise again.",a:"do",options:["do","to do","doing","did"]},
{q:"I didn't go out ___ the rain.",a:"because of",options:["although","because","because of","despite"]},
{q:"He denied ___ the window.",a:"breaking",options:["break","to break","breaking","broke"]},

{q:"The students ___ by the principal yesterday.",a:"were congratulated",options:["congratulated","were congratulated","have congratulated","are congratulating"]},
{q:"She asked me what time the train ___ .",a:"left",options:["leaves","left","has left","is leaving"]},
{q:"This is ___ interesting book.",a:"an",options:["a","an","the","no article"]},
{q:"Tom is ___ than his brother.",a:"less patient",options:["patient","less patient","least patient","more patiently"]},
{q:"She has been studying English ___ three hours.",a:"for",options:["since","for","during","while"]},
{q:"The room was too noisy ___ concentrate.",a:"to",options:["for","to","so","that"]},
{q:"I haven't seen him ___ Monday.",a:"since",options:["for","since","during","while"]},
{q:"Would you mind ___ the window?",a:"opening",options:["open","to open","opening","opened"]},
{q:"The project ___ by next week.",a:"will be finished",options:["finishes","finished","will be finished","will finish"]},
{q:"He speaks English ___ .",a:"fluently",options:["fluent","fluently","more fluent","fluency"]},

{q:"If I had known about the party, I ___ .",a:"would have come",options:["come","would come","would have come","came"]},
{q:"You ___ tell anyone. It's a secret.",a:"mustn't",options:["mustn't","should","can","might"]},
{q:"The girl ___ lives next door is very friendly.",a:"who",options:["who","whose","which","where"]},
{q:"I ___ my keys, so I can't open the door.",a:"have lost",options:["lose","lost","have lost","had lost"]},
{q:"He wasn't hungry ___ he ate a sandwich.",a:"but",options:["because","although","but","so"]},
{q:"This problem is ___ difficult for me.",a:"too",options:["so","too","such","very"]},
{q:"She said she ___ help me the next day.",a:"would",options:["will","would","can","shall"]},
{q:"The lesson was ___ than expected.",a:"more useful",options:["useful","more useful","most useful","usefuller"]},
{q:"I look forward to ___ from you soon.",a:"hearing",options:["hear","to hear","hearing","heard"]},
{q:"She ___ her homework before dinner every day.",a:"finishes",options:["finish","finishes","finished","finishing"]}

];
