// =====================================================
// FULL CEFR B2 GRAMMAR BANK
// High Quality / Single Correct Answer
// CEFR B2 Compatible
// 100 Questions / No topic field
// =====================================================

window.grammar_B2 = [

{q:"If I ___ about the traffic, I would have left earlier.",a:"had known",options:["knew","had known","would know","have known"]},
{q:"By the time we arrived, the meeting ___.",a:"had already started",options:["already started","had already started","has already started","was already starting"]},
{q:"She said she ___ the report by Friday.",a:"would finish",options:["will finish","would finish","finished","has finished"]},
{q:"At this time tomorrow, I ___ on the beach.",a:"will be relaxing",options:["relax","will relax","will be relaxing","am relaxing"]},
{q:"You ___ smoke in this building. It’s forbidden.",a:"must not",options:["don’t have to","must not","might not","would not"]},
{q:"He looks exhausted. He ___ all night.",a:"must have worked",options:["must have worked","can work","should work","might work"]},
{q:"If she ___ harder, she would be more confident now.",a:"had studied",options:["studied","had studied","would study","has studied"]},
{q:"I wish I ___ more time to travel.",a:"had",options:["have","had","would have","am having"]},
{q:"The project ___ before the deadline.",a:"was completed",options:["completed","was completed","has completing","was completing"]},
{q:"She made me ___ the problem again.",a:"explain",options:["to explain","explaining","explain","explained"]},

{q:"He denied ___ the money.",a:"taking",options:["take","to take","taking","taken"]},
{q:"Neither of the answers ___ correct.",a:"was",options:["were","was","are","be"]},
{q:"The woman ___ lives next door is a lawyer.",a:"who",options:["which","who","where","whose"]},
{q:"___ is important to stay calm during an interview.",a:"It",options:["There","It","This","That"]},
{q:"She ___ finished the task because the lights are still on.",a:"can’t have",options:["must have","can’t have","should have","would have"]},
{q:"Hardly ___ the train left the station.",a:"had we boarded when",options:["we had boarded when","had we boarded when","we boarded","did we board when"]},
{q:"The more you practice, ___ you become.",a:"the better",options:["better","the better","the best","more better"]},
{q:"This is by far ___ book I have ever read.",a:"the most inspiring",options:["more inspiring","the inspiring","the most inspiring","most inspiring"]},
{q:"He apologized ___ being late.",a:"for",options:["about","for","with","at"]},
{q:"___ the rain, we continued the match.",a:"Despite",options:["Because","Despite","Although","Due"]},

{q:"She spoke quietly so as not ___ the baby.",a:"to wake",options:["wake","to wake","waking","woke"]},
{q:"The manager demanded that the report ___ immediately.",a:"be sent",options:["is sent","be sent","was sent","sent"]},
{q:"Not only ___ late, but he also forgot the documents.",a:"was he",options:["he was","was he","he had","did he"]},
{q:"The film was so boring that we ended up ___.",a:"leaving early",options:["leave early","to leave early","leaving early","left early"]},
{q:"I’d rather you ___ me before coming over.",a:"called",options:["call","called","would call","have called"]},
{q:"The house ___ last year has already been sold.",a:"built",options:["building","built","was built","has built"]},
{q:"He’s one of the most talented people ___.",a:"I’ve ever met",options:["I ever met","I’ve ever met","I had ever met","I meet"]},
{q:"No sooner ___ the speech than the audience applauded.",a:"had she finished",options:["she finished","had she finished","did she finish","she had finished"]},
{q:"You need to take responsibility ___ your actions.",a:"for",options:["to","for","with","at"]},
{q:"I’m not used to ___ up this early.",a:"getting",options:["get","got","getting","have got"]},

{q:"The scientist ___ discovery changed medicine forever won an award.",a:"whose",options:["who","which","whose","whom"]},
{q:"He acts as if he ___ everything.",a:"knew",options:["knows","knew","has known","would know"]},
{q:"The company is expected ___ profits this year.",a:"to increase",options:["increase","to increase","increasing","increased"]},
{q:"Only after the meeting ___ the truth.",a:"did we learn",options:["we learned","did we learn","we had learned","had we learned"]},
{q:"She suggested ___ a break before continuing.",a:"taking",options:["take","to take","taking","taken"]},
{q:"The lecture was too complicated for me ___.",a:"to understand",options:["understand","understanding","to understand","understood"]},
{q:"He accused me ___ lying.",a:"of",options:["for","with","of","about"]},
{q:"If only I ___ more careful yesterday.",a:"had been",options:["was","had been","would be","have been"]},
{q:"The roads are wet. It ___ last night.",a:"must have rained",options:["must rain","must have rained","should rain","can rain"]},
{q:"The teacher let the students ___ early.",a:"leave",options:["to leave","leave","leaving","left"]},

{q:"The proposal was rejected ___ its high cost.",a:"because of",options:["although","despite","because of","however"]},
{q:"He has difficulty ___ in public.",a:"speaking",options:["speak","to speak","speaking","spoken"]},
{q:"The movie was not as exciting as I ___.",a:"had expected",options:["expect","expected","had expected","have expected"]},
{q:"Under no circumstances ___ this information be shared.",a:"should",options:["should","would","can","must"]},
{q:"The factory is said ___ thousands of products daily.",a:"to produce",options:["produce","to produce","producing","produced"]},
{q:"I regret ___ you that your application was unsuccessful.",a:"to inform",options:["inform","informing","to inform","informed"]},
{q:"He went to bed early in order ___ rested.",a:"to feel",options:["feel","feeling","to feel","felt"]},
{q:"The woman to ___ I spoke was very helpful.",a:"whom",options:["who","whose","whom","which"]},
{q:"The book ___ by millions around the world.",a:"has been read",options:["read","has been read","was reading","has reading"]},
{q:"Scarcely ___ the room when the phone rang.",a:"had I entered",options:["I entered","had I entered","did I enter","I had entered"]},

{q:"She would rather ___ at home tonight.",a:"stay",options:["stays","stayed","stay","staying"]},
{q:"We are looking forward to ___ from you soon.",a:"hearing",options:["hear","to hear","hearing","heard"]},
{q:"The article raised several issues worthy of ___.",a:"discussion",options:["discuss","discussion","discussing","discussed"]},
{q:"Had I known about the event, I ___ attended.",a:"would have",options:["would","would have","will have","had"]},
{q:"He denied ___ responsible for the mistake.",a:"being",options:["be","to be","being","been"]},
{q:"The results were far more impressive than we ___.",a:"had anticipated",options:["anticipate","anticipated","had anticipated","have anticipated"]},
{q:"Not until midnight ___ home.",a:"did they return",options:["they returned","did they return","had they returned","they had returned"]},
{q:"The lecture was interesting enough ___ everyone engaged.",a:"to keep",options:["keep","keeping","to keep","kept"]},
{q:"He succeeded ___ solving the problem.",a:"in",options:["on","at","in","for"]},
{q:"She speaks English fluently, ___ surprises many people.",a:"which",options:["who","which","what","whose"]},

{q:"I’d rather not ___ about it right now.",a:"talk",options:["to talk","talk","talking","talked"]},
{q:"The car needs ___.",a:"repairing",options:["repair","to repair","repairing","repaired"]},
{q:"So difficult ___ that very few students passed.",a:"was the exam",options:["the exam was","was the exam","did the exam","the exam did"]},
{q:"The company aims ___ its services internationally.",a:"to expand",options:["expand","expanding","to expand","expanded"]},
{q:"He objected ___ treated unfairly.",a:"to being",options:["for being","to being","being","to be"]},
{q:"The bridge ___ next year will reduce traffic.",a:"to be completed",options:["completing","completed","to be completed","having completed"]},
{q:"She isn’t tall enough ___ the shelf.",a:"to reach",options:["reach","reaching","to reach","reached"]},
{q:"The police are investigating the man ___ yesterday.",a:"arrested",options:["arrest","arresting","arrested","was arrested"]},
{q:"You should avoid ___ sensitive topics at dinner.",a:"discussing",options:["discuss","to discuss","discussing","discussed"]},
{q:"The speech was delivered clearly and ___.",a:"confidently",options:["confidence","confident","confidently","confidentness"]},

{q:"He behaved as though nothing ___.",a:"had happened",options:["happened","had happened","has happened","would happen"]},
{q:"The meeting has been postponed ___ further notice.",a:"until",options:["by","until","for","since"]},
{q:"She warned him ___ late again.",a:"not to be",options:["don’t be","not be","not to be","to not being"]},
{q:"The issue is too complex ___ quickly.",a:"to solve",options:["solve","solving","to solve","solved"]},
{q:"It’s high time we ___ a decision.",a:"made",options:["make","made","have made","would make"]},
{q:"Little ___ about the consequences at the time.",a:"did they know",options:["they knew","did they know","had they known","they had known"]},
{q:"The report needs ___ before publication.",a:"reviewing",options:["review","reviewed","reviewing","to reviewing"]},
{q:"He insisted ___ paying for dinner.",a:"on",options:["at","to","on","for"]},
{q:"The instructions were so unclear that we couldn’t ___ them.",a:"follow",options:["following","follow","followed","to follow"]},
{q:"The new policy will come into ___ next month.",a:"effect",options:["affect","effect","result","impact"]},

{q:"She denied ___ the confidential information.",a:"sharing",options:["share","to share","sharing","shared"]},
{q:"He is believed ___ abroad for several years.",a:"to have lived",options:["living","to live","to have lived","lived"]},
{q:"Rarely ___ such a beautiful performance.",a:"have I seen",options:["I have seen","have I seen","I saw","did I saw"]},
{q:"The company prevented the data ___ leaked.",a:"from being",options:["to be","being","from being","from be"]},
{q:"She admitted ___ the mistake immediately.",a:"making",options:["make","to make","making","made"]},
{q:"The teacher encouraged students ___ independently.",a:"to think",options:["think","thinking","to think","thought"]},
{q:"Despite ___ hard, he didn’t pass the test.",a:"studying",options:["study","studied","studying","to study"]},
{q:"The restaurant is known ___ its excellent service.",a:"for",options:["about","for","with","to"]},
{q:"I can’t imagine ___ in such a crowded city.",a:"living",options:["live","to live","living","lived"]},
{q:"The room appeared ___ recently.",a:"to have been painted",options:["painted","painting","to paint","to have been painted"]},

{q:"The manager requested that everyone ___ on time.",a:"be",options:["is","was","be","are"]},
{q:"No matter how hard he tried, he couldn’t ___ the problem.",a:"solve",options:["solving","solve","solved","to solving"]},
{q:"The documents are supposed ___ by noon.",a:"to be delivered",options:["deliver","delivering","to be delivered","delivered"]},
{q:"She left early so that she ___ the traffic.",a:"could avoid",options:["avoids","could avoid","avoided","would avoid"]},
{q:"The audience remained silent throughout the ___.",a:"performance",options:["perform","performed","performance","performing"]},
{q:"He apologized for ___ rude during the meeting.",a:"being",options:["be","to be","being","been"]},
{q:"The scientist devoted his life to ___ cancer.",a:"researching",options:["research","researched","researching","to research"]},
{q:"Only by working together ___ success.",a:"can we achieve",options:["we can achieve","can we achieve","we achieved","did we achieve"]},
{q:"The book is considered ___ one of the best novels ever written.",a:"to be",options:["being","to be","be","been"]},
{q:"He was too tired ___ concentrating.",a:"to continue",options:["continue","continuing","to continue","continued"]},

{q:"The article focuses ___ environmental issues.",a:"on",options:["in","at","on","for"]},
{q:"She objected to ___ as inexperienced.",a:"being treated",options:["treat","treated","being treated","be treated"]},
{q:"The results turned out ___ than expected.",a:"better",options:["best","better","more good","well"]},
{q:"If the weather improves, we ___ hiking tomorrow.",a:"will go",options:["go","went","will go","would go"]},
{q:"He admitted that he ___ the instructions incorrectly.",a:"had understood",options:["understands","understood","had understood","has understood"]},
{q:"The plan failed because nobody was willing ___ responsibility.",a:"to take",options:["take","taking","to take","taken"]}

];
