window.grammar_A2 = [

{ q: "I went to the market ___ buy some fruit.", a: "to", options: ["for","to","because","with"] },
{ q: "This bag is ___ carrying books.", a: "for", options: ["to","with","from","for"] },
{ q: "She enjoys ___ books at night.", a: "reading", options: ["reading","to read","read","reader"] },
{ q: "They want ___ a new language.", a: "to learn", options: ["learning","to learn","learned","learnt"] },
{ q: "He decided ___ early.", a: "to leave", options: ["leaving","left","leave","to leave"] },
{ q: "I am interested in ___ English.", a: "learning", options: ["learning","to learn","learn","learnt"] },
{ q: "She promised ___ me tomorrow.", a: "to call", options: ["calling","to call","call","called"] },
{ q: "We finished ___ dinner at 8 PM.", a: "eating", options: ["to eat","eat","eating","eaten"] },
{ q: "He forgot ___ the window.", a: "to close", options: ["to close","closing","closed","close"] },
{ q: "My brother loves ___ football.", a: "playing", options: ["to play","played","playing","play"] },

{ q: "___ am very tired today.", a: "I", options: ["I","Me","Mine","My"] },
{ q: "Sarah invited ___ to her party.", a: "me", options: ["I","me","mine","my"] },
{ q: "That bicycle is ___.", a: "mine", options: ["my","me","mine","ours"] },
{ q: "We cleaned ___ room yesterday.", a: "our", options: ["our","ours","us","their"] },
{ q: "The dog followed ___.", a: "them", options: ["their","theirs","them","they"] },
{ q: "This phone belongs to ___.", a: "him", options: ["his","he","him","himself"] },
{ q: "Is this jacket ___?", a: "yours", options: ["your","yours","you","yourselves"] },
{ q: "___ teacher is very kind.", a: "Their", options: ["Theirs","Them","Their","They"] },
{ q: "Lisa hurt ___ while cooking.", a: "herself", options: ["hers","herself","her","she"] },
{ q: "The children washed ___ hands.", a: "their", options: ["their","theirs","them","they"] },

{ q: "There is ___ in the fridge to eat.", a: "something", options: ["anything","nothing","something","everything"] },
{ q: "I don't know ___ about this topic.", a: "anything", options: ["something","everything","anything","nothing"] },
{ q: "___ called you this morning.", a: "Somebody", options: ["Somebody","Nobody","Anybody","Everybody"] },
{ q: "There was ___ in the room.", a: "nobody", options: ["somebody","nobody","everybody","anybody"] },
{ q: "Did you see ___ at the park?", a: "anyone", options: ["someone","everyone","nobody","anyone"] },
{ q: "I need ___ to help me move this table.", a: "someone", options: ["someone","anyone","no one","everyone"] },
{ q: "There isn't ___ milk left.", a: "any", options: ["many","any","few","much"] },
{ q: "We have ___ apples in the basket.", a: "many", options: ["much","little","many","few"] },
{ q: "There is very ___ water in the bottle.", a: "little", options: ["few","little","many","much"] },
{ q: "Only a ___ students were absent today.", a: "few", options: ["little","much","many","few"] },

{ q: "The box is ___ heavy for me.", a: "too", options: ["enough","very","too","so"] },
{ q: "We don't have ___ chairs for everyone.", a: "enough", options: ["too","enough","much","many"] },
{ q: "She ate ___ much chocolate.", a: "too", options: ["too","enough","few","many"] },
{ q: "He isn't tall ___.", a: "enough", options: ["too","many","enough","much"] },
{ q: "There are ___ many cars on the road.", a: "too", options: ["enough","little","few","too"] },
{ q: "Most ___ my friends like music.", a: "of", options: ["from","of","with","in"] },
{ q: "___ people enjoy holidays.", a: "Most", options: ["Much","Few","Most","Little"] },
{ q: "Anna is the ___ intelligent student here.", a: "most", options: ["more","much","most","many"] },
{ q: "This is the ___ interesting book I've read.", a: "most", options: ["more","most","many","much"] },
{ q: "___ of the cake was eaten.", a: "Most", options: ["Most","Many","Few","Some"] },

{ q: "The girl ___ lives next door is my cousin.", a: "who", options: ["which","where","who","that"] },
{ q: "The restaurant ___ we ate was excellent.", a: "where", options: ["who","where","that","which"] },
{ q: "I lost the keys ___ you gave me.", a: "that", options: ["where","who","that","which"] },
{ q: "The movie ___ we watched was funny.", a: "which", options: ["who","which","where","that"] },
{ q: "The man ___ called yesterday is my uncle.", a: "who", options: ["which","where","who","that"] },
{ q: "This is the shop ___ I bought my shoes.", a: "where", options: ["which","who","where","that"] },
{ q: "The cake ___ she made tastes delicious.", a: "that", options: ["where","that","who","which"] },
{ q: "The teacher ___ teaches us math is very strict.", a: "who", options: ["who","which","where","that"] },
{ q: "The book ___ is on the table is mine.", a: "which", options: ["who","where","which","that"] },
{ q: "I visited the town ___ my father was born.", a: "where", options: ["who","which","that","where"] },

{ q: "I love jazz music. — So ___ I.", a: "do", options: ["am","do","have","can"] },
{ q: "She isn't tired. — Neither ___ he.", a: "is", options: ["does","has","is","can"] },
{ q: "We can swim. — So ___ they.", a: "can", options: ["are","do","can","have"] },
{ q: "Tom doesn't eat meat. — Neither ___ Sarah.", a: "does", options: ["is","does","can","has"] },
{ q: "I ___ finished my homework.", a: "have", options: ["do","be","have","has"] },
{ q: "She ___ working right now.", a: "is", options: ["does","is","has","was"] },
{ q: "___ you like coffee?", a: "Do", options: ["Do","Have","Are","Did"] },
{ q: "They ___ already eaten lunch.", a: "have", options: ["are","do","have","has"] },
{ q: "My father ___ watching TV now.", a: "is", options: ["does","has","was","is"] },
{ q: "___ she play the piano?", a: "Does", options: ["Is","Does","Has","Did"] },

{ q: "My house is ___ than yours.", a: "bigger", options: ["biggest","more big","bigger","big"] },
{ q: "This is the ___ restaurant in town.", a: "best", options: ["better","best","good","well"] },
{ q: "He runs ___ than me.", a: "faster", options: ["fastest","more fast","faster","fast"] },
{ q: "Today is the ___ day of the week.", a: "hottest", options: ["hotter","hottest","more hot","hot"] },
{ q: "My sister speaks English ___ than I do.", a: "more fluently", options: ["most fluently","fluent","more fluently","fluently"] },
{ q: "This exercise is ___ than the last one.", a: "easier", options: ["easiest","easier","more easy","easy"] },
{ q: "Mount Everest is the ___ mountain in the world.", a: "highest", options: ["higher","more high","highest","high"] },
{ q: "He arrived ___ than expected.", a: "earlier", options: ["earliest","earlier","more early","early"] },
{ q: "That was the ___ movie I've ever seen.", a: "worst", options: ["worse","bad","worst","badly"] },
{ q: "She dances ___ than her brother.", a: "better", options: ["best","better","good","well"] },

{ q: "We no ___ live in Ankara.", a: "longer", options: ["more","later","longer","still"] },
{ q: "I don't work there ___ .", a: "anymore", options: ["already","anymore","still","yet"] },
{ q: "She doesn't study French any ___ .", a: "longer", options: ["more","yet","longer","still"] },
{ q: "Although it was raining, we ___ outside.", a: "went", options: ["go","went","going","gone"] },
{ q: "I stayed home ___ I was sick.", a: "because", options: ["although","however","because","so"] },
{ q: "He studied hard, ___ he passed the exam.", a: "so", options: ["although","however","so","because"] },
{ q: "I was tired; ___, I finished my work.", a: "however", options: ["because","however","so","although"] },
{ q: "___ she was young, she was very brave.", a: "Although", options: ["Because","So","Although","However"] },
{ q: "Call me ___ you arrive.", a: "when", options: ["because","although","when","after"] },
{ q: "I washed the dishes ___ dinner.", a: "after", options: ["although","however","after","before"] },

{ q: "The cat jumped ___ the wall.", a: "over", options: ["along","through","over","under"] },
{ q: "We walked ___ the river.", a: "along", options: ["across","along","under","through"] },
{ q: "She ran ___ the street quickly.", a: "across", options: ["through","over","across","under"] },
{ q: "The train arrived ___ time.", a: "on", options: ["in","at","on","by"] },
{ q: "We reached the airport just ___ time.", a: "in", options: ["on","in","at","by"] },
{ q: "___ the end, we decided to stay home.", a: "In", options: ["At","On","In","By"] },
{ q: "There is a bakery ___ the end of the street.", a: "at", options: ["in","at","on","by"] },
{ q: "The dog ran ___ the tunnel.", a: "through", options: ["over","along","through","across"] },
{ q: "He walked ___ me without speaking.", a: "past", options: ["across","past","through","along"] },
{ q: "The bird flew ___ the lake.", a: "over", options: ["along","under","over","through"] },

{ q: "___ are you talking to?", a: "Who", options: ["What","Who","Where","Why"] },
{ q: "___ called you last night?", a: "Who", options: ["Whose","Which","Who","What"] },
{ q: "___ did you put my keys?", a: "Where", options: ["Why","Where","When","How"] },
{ q: "___ are they laughing?", a: "Why", options: ["Who","How","Why","When"] },
{ q: "___ does this train leave?", a: "When", options: ["Where","Who","When","Why"] },
{ q: "___ is your favorite actor?", a: "Who", options: ["What","Who","When","Where"] },
{ q: "___ are you waiting for?", a: "Who", options: ["Why","Which","Who","What"] },
{ q: "___ do you go to school?", a: "How", options: ["Who","How","Which","When"] },
{ q: "___ broke the window?", a: "Who", options: ["Where","When","Who","Why"] },
{ q: "___ are you interested in?", a: "What", options: ["Who","Where","What","When"] }

];
